services:
  - type: web
    name: jameya-backend
    runtime: node
    plan: starter
    buildCommand: npm install --include=dev && npm run build
    startCommand: npx prisma migrate deploy && npx prisma db seed && npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: jameya-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ADMIN_JWT_ACCESS_SECRET
        generateValue: true
      - key: ADMIN_JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRATION
        value: 15m
      - key: JWT_REFRESH_EXPIRATION
        value: 30d
      - key: ADMIN_JWT_ACCESS_EXPIRATION
        value: 15m
      - key: ADMIN_JWT_REFRESH_EXPIRATION
        value: 8h
      - key: OTP_DRIVER
        value: email
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM
        value: "Jameya Support <onboarding@resend.dev>"
      - key: SEED_ADMIN_EMAIL
        value: "admin@jameya.local"
      - key: SEED_ADMIN_PASSWORD
        value: "ChangeMe123!"

databases:
  - name: jameya-db
    databaseName: jameya_db
    user: jameya_user
    plan: starter
